/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.pessoa;
import java.util.ArrayList;

/**
 *
 * @author dbezerra
 */
public class listagem extends javax.swing.JFrame {

    private ArrayList<pessoa> listadepessoa = new ArrayList();
    /**
     * Creates new form listagem
     */
    public listagem() {
        initComponents();
    }
    public void ListarPessoas(){
        getTextlistapessoas().setText("");
        for (int i = 0; i < getListadepessoa().size(); i++) {
            getTextlistapessoas().setText(getTextlistapessoas().getText() + 
                 i + " " + getListadepessoa().get(i).MostrarDados() + "\n" );   
        }
}
    
    public void cadastrarpessoas(pessoa pessoinha){
        getListadepessoa().add(pessoinha);
        
    }
    public void atualizarPessoa(int id ,String novoNome, String novoCPF, int novaIdade){
        
            getListadepessoa().get(id) .setNome(novoNome);
            getListadepessoa().get(id) .setIdade(novaIdade);
            getListadepessoa().get(id) .setCpf(novoCPF);
        }
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botaocadastro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        butaodeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textlistapessoas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textIdDelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("TELA DE LISTAGEM");

        botaocadastro.setText("cadastrar");
        botaocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocadastroActionPerformed(evt);
            }
        });

        jButton2.setText("alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        butaodeletar.setText("deletar");
        butaodeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaodeletarActionPerformed(evt);
            }
        });

        textlistapessoas.setColumns(20);
        textlistapessoas.setRows(5);
        jScrollPane1.setViewportView(textlistapessoas);

        jLabel1.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaocadastro)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2)
                                .addGap(48, 48, 48)
                                .addComponent(butaodeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textIdDelete)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaocadastro)
                    .addComponent(jButton2)
                    .addComponent(butaodeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocadastroActionPerformed
        // TODO add your handling code here:
      
       cadastro telacad = new cadastro(this);
              setVisible(false);
              telacad.setVisible(true);

            
    }//GEN-LAST:event_botaocadastroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         atualizar telacad = new atualizar(this);
              setVisible(false);
              telacad.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butaodeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaodeletarActionPerformed
        // TODO add your handling code here:
        listadepessoa.remove(Integer.parseInt(textIdDelete.getText()));
        
        ListarPessoas();
    }//GEN-LAST:event_butaodeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaocadastro;
    private javax.swing.JButton butaodeletar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textIdDelete;
    private javax.swing.JTextArea textlistapessoas;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the listadepessoa
     */
    public ArrayList<pessoa> getListadepessoa() {
        return listadepessoa;
    }

    /**
     * @param listadepessoa the listadepessoa to set
     */
    public void setListadepessoa(ArrayList<pessoa> listadepessoa) {
        this.listadepessoa = listadepessoa;
    }

    /**
     * @return the botaocadastro
     */
    public javax.swing.JButton getBotaocadastro() {
        return botaocadastro;
    }

    /**
     * @param botaocadastro the botaocadastro to set
     */
    public void setBotaocadastro(javax.swing.JButton botaocadastro) {
        this.botaocadastro = botaocadastro;
    }

    /**
     * @return the butaodeletar
     */
    public javax.swing.JButton getButaodeletar() {
        return butaodeletar;
    }

    /**
     * @param butaodeletar the butaodeletar to set
     */
    public void setButaodeletar(javax.swing.JButton butaodeletar) {
        this.butaodeletar = butaodeletar;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the textlistapessoas
     */
    public javax.swing.JTextArea getTextlistapessoas() {
        return textlistapessoas;
    }

    /**
     * @param textlistapessoas the textlistapessoas to set
     */
    public void setTextlistapessoas(javax.swing.JTextArea textlistapessoas) {
        this.textlistapessoas = textlistapessoas;
    }
}
